version: '3'
services:
  blowhorn-nginx:
    image: nginx:1.13
    ports:
        - "80:80"
        - "443:443"
    volumes:
        - /etc/nginx:/etc/nginx
        - /etc/letsencrypt:/etc/letsencrypt
  blowhorn-metabase:
    image: metabase/metabase
    ports:
        - "3000:3000"
    healthcheck:
      test: wget -q -s -T 5 localhost:3000 ||exit 1
      interval: 15s
      timeout: 7s
      retries: 1
    environment:
      - MB_DB_TYPE=postgres
      - MB_DB_DBNAME=metabase_db
      - MB_DB_PORT=5432
      - MB_DB_USER=report_user
      - MB_DB_PASS=report_user
      - MB_DB_HOST=reportingnew.c8zqdbei6lcp.us-east-2.rds.amazonaws.com
      - MB_JETTY_HOST=0.0.0.0
      - JAVA_TOOL_OPTIONS=-Xmx4g
#      - MB_JETTY_SSL=true
#      - MB_JETTY_SSL_Port=8443
#      - MB_JETTY_SSL_Keystore=/etc/cert/KeyStore.jks
#      - MB_JETTY_SSL_Keystore_Password=storepass
    restart: on-failure:3
    